language: go

go:
  - 1.20.x
  - 1.21.x

services:
  - docker

script:
  - docker pull confluentinc/confluent-local:7.5.3
  - go build cmd/kafka-idle-topics/kafka-idle-topics.go
  - cd cmd/kafka-idle-topics/
  - docker-compose up -d
  - go test

addons:
  sonarcloud:
    organization: "abraham-leal"
