language: go

go:
  - 1.15.x
  - 1.16.x

services:
  - docker

script:
  - docker pull confluentinc/cp-zookeeper:6.1.0
  - docker pull confluentinc/cp-server:6.1.0
  - go build cmd/idleTopicChecker/idleTopicChecker.go
  - cd cmd/idleTopicChecker/
  - docker-compose up -d
  - go test

addons:
  sonarcloud:
    organization: "abraham-leal"